version: '3.8'

services:
  thorium-browser:
    image: ghcr.io/bropines/thorium-docker:latest
    container_name: thorium-browser
    restart: unless-stopped
    ports:
      - "9222:9222"
    volumes:
      - ./MSG/thorium_profile:/data/thorium_profile
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M